export const EVENT_CREATE_SUCCESS = 'EVENT_CREATE_SUCCESS';
export const EVENT_CREATE_FAILED = 'EVENT_CREATE_FAILED';
export const EVENT_CREATE_REQUEST = 'EVENT_CREATE_REQUEST';

export const EVENT_GET_SUCCESS = 'EVENT_GET_SUCCESS';
export const EVENT_GET_FAILED = 'EVENT_GET_FAILED';
export const EVENT_GET_REQUEST = 'EVENT_GET_REQUEST';
export const EVENT_GET_RESET = 'EVENT_GET_RESET';

export const CLEAR_ERROR = 'CLEAR_ERROR';
