export const EVENT_CREATE_SUCCESS = 'EVENT_CREATE_SUCCESS';
export const EVENT_CREATE_FAILED = 'EVENT_CREATE_FAILED';
export const EVENT_CREATE_REQUEST = 'EVENT_CREATE_REQUEST';

export const EVENT_GET_SUCCESS = 'EVENT_GET_SUCCESS';
export const EVENT_GET_FAILED = 'EVENT_GET_FAILED';
export const EVENT_GET_REQUEST = 'EVENT_GET_REQUEST';
export const EVENT_GET_RESET = 'EVENT_GET_RESET';

export const EVENT_SINGLE_SUCCESS = 'EVENT_SINGLE_SUCCESS';
export const EVENT_SINGLE_FAILED = 'EVENT_SINGLE_FAILED';
export const EVENT_SINGLE_REQUEST = 'EVENT_SINGLE_REQUEST';
export const EVENT_SINGLE_RESET = 'EVENT_SINGLE_RESET';

export const USER_EVENTS_SUCCESS = 'USER_EVENTS_SUCCESS';
export const USER_EVENTS_FAILED = 'USER_EVENTS_FAILED';
export const USER_EVENTS_REQUEST = 'USER_EVENTS_REQUEST';
export const USER_EVENTS_RESET = 'USER_EVENTS_RESET';

export const CLEAR_ERROR = 'CLEAR_ERROR';
