export const EVENT_CREATE_SUCCESS = 'EVENT_CREATE_SUCCESS';
export const EVENT_CREATE_FAILED = 'EVENT_CREATE_FAILED';
export const EVENT_CREATE_REQUEST = 'EVENT_CREATE_REQUEST';

export const CLEAR_ERROR = 'CLEAR_ERROR';
