export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED';
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';

export const USER_LOAD_SUCCESS = 'USER_LOAD_SUCCESS';
export const USER_LOAD_FAILED = 'USER_LOAD_FAILED';
export const USER_LOAD_REQUEST = 'USER_LOAD_REQUEST';

export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILED = 'USER_UPDATE_FAILED';
export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';

export const FIND_EMAIL_SUCCESS = 'FIND_EMAIL_SUCCESS';
export const FIND_EMAIL_FAILED = 'FIND_EMAIL_FAILED';
export const FIND_EMAIL_REQUEST = 'FIND_EMAIL_REQUEST';
export const FIND_EMAIL_RESET = 'FIND_EMAIL_RESET';

export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED';
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_RESET = 'FORGOT_PASSWORD_RESET';

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_RESET = 'RESET_PASSWORD_RESET';

export const CLEAR_ERROR = 'CLEAR_ERROR';
